package tn.esprit.spring.kaddem.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class UniversiteDTO {
    private String nomUniv;

    // Constructors, getters, and setters can be generated by Lombok
}
